version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - run: exit 0
  test:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Run .sh for validation
          command: bash .circleci/simple_script.sh
workflows:
  version: 2
  btd:
    jobs:
    - build
    - test